drop table if exists actividad cascade;
drop table if exists asignatura cascade;
drop table if exists carrera cascade;
drop table if exists carrera_coordinador cascade;
drop table if exists cursada cascade;
drop table if exists cursada_examen cascade;
drop table if exists docente cascade;
drop table if exists docente_asignatura cascade;
drop table if exists docente_examen cascade;
drop table if exists docente_horario_asignatura cascade;
drop table if exists estudiante_cursada cascade;
drop table if exists examen cascade;
drop table if exists horario_asignatura cascade;
drop table if exists horario_dias cascade;
drop table if exists inscripcion_carrera cascade;
drop table if exists password_reset_token cascade;
drop table if exists periodo_examen cascade;
drop table if exists previaturas cascade;
drop table if exists usuario cascade;
drop table if exists usuario_tr cascade;


create table actividad (
                           id_actividad integer generated by default as identity,
                           id_usuario integer not null,
                           fecha_hora timestamp(6),
                           accion varchar(255),
                           primary key (id_actividad)
);
    
create table asignatura (
                            activa boolean,
                            creditos integer,
                            id_asignatura integer generated by default as identity,
                            id_carrera integer not null,
                            tiene_examen boolean,
                            departamento varchar(255),
                            descripcion varchar(255),
                            nombre varchar(255),
                            primary key (id_asignatura)
);
    
create table carrera (
                         activa boolean,
                         duracion integer,
                         id_carrera integer generated by default as identity,
                         descripcion varchar(255),
                         nombre varchar(255),
                         requisitos varchar(255),
                         primary key (id_carrera)
);
    
create table carrera_coordinador (
                                     id_carrera integer not null,
                                     id_coordinador integer not null,
                                     idcc integer generated by default as identity,
                                     primary key (idcc)
);
    
create table cursada (
                         calificacion int default 0,
                         id_asignatura integer not null,
                         id_cursada integer generated by default as identity,
                         id_horario_asignatura integer not null,
                         resultado varchar(255) check (resultado in ('EXONERADO','EXAMEN','RECURSA','PENDIENTE')),
                         primary key (id_cursada)
);
    
create table cursada_examen (
                                calificacion int default 0,
                                id_cursada integer not null,
                                id_cursada_examen integer generated by default as identity,
                                id_examen integer not null,
                                cedula_estudiante varchar(255),
                                resultado varchar(255) check (resultado in ('APROBADO','REPROBADO','PENDIENTE')),
                                primary key (id_cursada_examen)
);
    
create table docente (
                         activo boolean,
                         codigo_docente integer,
                         id_docente integer generated by default as identity,
                         nombre varchar(255),
                         primary key (id_docente)
);
    
create table docente_asignatura (
                                    id_asignatura integer not null,
                                    id_docente integer not null,
                                    idda integer generated by default as identity,
                                    primary key (idda)
);
    
create table docente_examen (
                                id_docente integer not null,
                                id_examen integer not null,
                                idde integer generated by default as identity,
                                primary key (idde)
);
    
create table docente_horario_asignatura (
                                            id_docente integer not null,
                                            id_horario_asignatura integer not null,
                                            iddha integer generated by default as identity,
                                            primary key (iddha)
);
    
create table estudiante_cursada (
                                    id_cursada integer not null,
                                    id_estudiante integer not null,
                                    idec integer generated by default as identity,
                                    primary key (idec)
);
    
create table examen (
                        id_asignatura integer not null,
                        id_examen integer generated by default as identity,
                        id_periodo_examen integer not null,
                        fecha_hora timestamp(6),
                        primary key (id_examen)
);
    
create table horario_asignatura (
                                    anio integer check ((anio>=1900) and (anio<=2200)),
                                    id_asignatura integer not null,
                                    id_horario_asignatura integer generated by default as identity,
                                    primary key (id_horario_asignatura)
);

create table horario_dias (
                              id_horario_asignatura integer not null,
                              id_horario_dias integer generated by default as identity,
                              dia_semana varchar(255) check (dia_semana in ('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO')),
                              hora_fin varchar(255),
                              hora_inicio varchar(255),
                              primary key (id_horario_dias)
);
    
create table inscripcion_carrera (
                                     activa boolean,
                                     id_carrera integer not null,
                                     id_estudiante integer not null,
                                     id_inscripcion integer generated by default as identity,
                                     validada boolean,
                                     primary key (id_inscripcion)
);
    
create table password_reset_token (
                                      id integer generated by default as identity,
                                      user_id integer not null,
                                      expiry_date_time timestamp(6),
                                      token varchar(255),
                                      primary key (id)
);
    
create table periodo_examen (
                                fecha_fin date,
                                fecha_inicio date,
                                id_carrera integer not null,
                                id_periodo_examen integer generated by default as identity,
                                nombre varchar(255),
                                primary key (id_periodo_examen)
);
    
create table previaturas (
                             id_asignatura integer not null,
                             id_prev_asig integer generated by default as identity,
                             id_previa integer not null,
                             primary key (id_prev_asig)
);
    
create table usuario (
                         activo boolean,
                         id_usuario integer generated by default as identity,
                         validado boolean,
                         apellido varchar(255),
                         cedula varchar(255),
                         email varchar(255),
                         fecha_nacimiento varchar(255),
                         nombre varchar(255),
                         password varchar(255),
                         rol varchar(255),
                         primary key (id_usuario)
);
    
create table usuario_tr (
                            id_usuario integer not null unique,
                            idtr integer generated by default as identity,
                            jwt TEXT,
                            mobile_token varchar(255),
                            primary key (idtr)
);
    
alter table if exists actividad
    add constraint FKbs55aff4qv00qus6vb8m2qqph
    foreign key (id_usuario)
    references usuario;
    
alter table if exists asignatura
    add constraint FK61jd7ak32pfvbsyxwhmqgctqq
    foreign key (id_carrera)
    references carrera;
    
alter table if exists carrera_coordinador
    add constraint FKg7tig0yf4ctta54ehfgv9lyh5
    foreign key (id_carrera)
    references carrera;
    
alter table if exists carrera_coordinador
    add constraint FKc6elcp6ml1jrudlutvus3dtvr
    foreign key (id_coordinador)
    references usuario;
    
alter table if exists cursada
    add constraint FK9xw27sbdlb7trkr5isom9ifu
    foreign key (id_asignatura)
    references asignatura;
    
alter table if exists cursada
    add constraint FKj93wa4rjkegsbvmfu2ugl4i5k
    foreign key (id_horario_asignatura)
    references horario_asignatura;
    
alter table if exists cursada_examen
    add constraint FKeiqfny5176rdx672bdmva4nky
    foreign key (id_cursada)
    references cursada;
    
alter table if exists cursada_examen
    add constraint FK2c4f32fdx0u5lux9ih2yfqv4q
    foreign key (id_examen)
    references examen;
    
alter table if exists docente_asignatura
    add constraint FKeu81hqnw7vawefx95jmiw7p9
    foreign key (id_asignatura)
    references asignatura;
    
alter table if exists docente_asignatura
    add constraint FKs29r6ix4ib8f9tb09l7iaajgw
    foreign key (id_docente)
    references docente;
    
alter table if exists docente_examen
    add constraint FKfxep5y3r5er23k198hlnkmknx
    foreign key (id_docente)
    references docente;
    
alter table if exists docente_examen
    add constraint FK6svsbdoi625hmt45k0o1kbiot
    foreign key (id_examen)
    references examen;
    
alter table if exists docente_horario_asignatura
    add constraint FK7djs2jtykjchivh9c0bfrux9u
    foreign key (id_docente)
    references docente;
    
alter table if exists docente_horario_asignatura
    add constraint FKeoqg79f5vbnelhd3eskacw1wr
    foreign key (id_horario_asignatura)
    references horario_asignatura;
    
alter table if exists estudiante_cursada
    add constraint FKbifhf9a2bi7srlp4fdyscywf7
    foreign key (id_cursada)
    references cursada;
    
alter table if exists estudiante_cursada
    add constraint FK1vm71ajofe2ff6sfqh42g2gjw
    foreign key (id_estudiante)
    references usuario;
    
alter table if exists examen
    add constraint FKqq57kbxu6jbrrewxti6ttwj9k
    foreign key (id_asignatura)
    references asignatura;
    
alter table if exists examen
    add constraint FK1igw529bps4c5rcv1lwufb2pb
    foreign key (id_periodo_examen)
    references periodo_examen;
    
alter table if exists horario_asignatura
    add constraint FKsam2f2m31w9vowmrkvbft6mtw
    foreign key (id_asignatura)
    references asignatura;

alter table if exists horario_dias
    add constraint FKabtvan3ct66otjy04fw3liox8
    foreign key (id_horario_asignatura)
    references horario_asignatura;
    
alter table if exists inscripcion_carrera
    add constraint FK9fiukma62hs7ql3c0ufd53ghb
    foreign key (id_carrera)
    references carrera;
    
alter table if exists inscripcion_carrera
    add constraint FKngc14mw8p81tsircskvsmky4d
    foreign key (id_estudiante)
    references usuario;
    
alter table if exists password_reset_token
    add constraint FKctt15hotnxj2p53cimeh4lunj
    foreign key (user_id)
    references usuario;
    
alter table if exists periodo_examen
    add constraint FK938u4i2o756dgf8t06s3lvpit
    foreign key (id_carrera)
    references carrera;
    
alter table if exists previaturas
    add constraint FKj9sqnirqrmj337s4ksqqfubc1
    foreign key (id_asignatura)
    references asignatura;
    
alter table if exists previaturas
    add constraint FKg0tc6obd84g4tomxa5k0d3xxv
    foreign key (id_previa)
    references asignatura;
    
alter table if exists usuario_tr
    add constraint FKkdc4vawaaqwaq8ruquk2kak3i
    foreign key (id_usuario)
    references usuario;

